package constant

var Languages = map[string]string{
	"Albanian":             "Albanian",
	"Arabic":               "Arabic",
	"Armenian":             "Armenian",
	"Belarusian":           "Belarusian",
	"Bengali":              "Bengali",
	"Brazilian Portuguese": "Brazilian Portuguese",
	"Bulgarian":            "Bulgarian",
	"Cantonese (Yue)":      "Cantonese (Yue)",
	"Croatian":             "Croatian",
	"Czech":                "Czech",
	"Danish":               "Danish",
	"Dutch":                "Dutch",
	"English":              "English",
	"Estonian":             "Estonian",
	"Finnish":              "Finnish",
	"French":               "French",
	"German":               "German",
	"Hindi":                "Hindi",
	"Hungarian":            "Hungarian",
	"Indonesian":           "Indonesian",
	"Irish":                "Irish",
	"Italian":              "Italian",
	"Japanese":             "Japanese",
	"Javanese":             "Javanese",
	"Kannada":              "Kannada",
	"Korean":               "Korean",
	"Latvian":              "Latvian",
	"Lithuanian":           "Lithuanian",
	"Macedonian":           "Macedonian",
	"Malay":                "Malay",
	"Maltese":              "Maltese",
	"Mandarin Chinese":     "Mandarin Chinese",
	"Norwegian":            "Norwegian",
	"Persian (Farsi)":      "Persian (Farsi)",
	"Polish":               "Polish",
	"Portuguese":           "Portuguese",
	"Romanian":             "Romanian",
	"Russian":              "Russian",
	"Serbian":              "Serbian",
	"Sinhala":              "Sinhala",
	"Slovak":               "Slovak",
	"Slovenian":            "Slovenian",
	"Ukrainian":            "Ukrainian",
	"Urdu":                 "Urdu",
	"Uzbek":                "Uzbek",
	"Vietnamese":           "Vietnamese",
}
